# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            adarsh kumar
tagline:          'a homo-sapien'
description:      '-.-.-.-.'
url:              adarsh-kr.github.io
baseurl:          /adarsh-kr.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-paginate
  - jekyll-gist
  - github-pages

