# Setup
title: Adarsh Kumar
tagline: Moving towards convergence
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


pages_list:       
  About: '/about'
  Publications: '/publications'
  Quotes/Shayari: '/quotes'
  Dedication: '/dedication'


# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Adarsh Kumar
  url: https://adarsh-kr.github.io/
  email: adi28kr@gmail.com

# Custom vars
version: 3.0.0
